# Generated by Django 3.1.7 on 2021-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfHeader',
            fields=[
                ('pdf_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_index', models.IntegerField()),
                ('particulars_index', models.IntegerField()),
                ('instrument_index', models.IntegerField()),
                ('withdraw_index', models.IntegerField()),
                ('deposit_index', models.IntegerField()),
                ('balance_index', models.IntegerField()),
            ],
        ),
    ]
