# Generated by Django 3.1.7 on 2021-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfheader',
            name='balance_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='date_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='deposit_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='instrument_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='particulars_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='withdraw_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
