# Generated by Django 3.1.7 on 2021-06-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanpdf', '0002_auto_20210605_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfheader',
            old_name='date_index',
            new_name='dates_index',
        ),
    ]
