# Generated by Django 3.1.7 on 2021-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpdf', '0003_auto_20210605_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfheader',
            name='balance_index',
            field=models.IntegerField(default=-2021),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='dates_index',
            field=models.IntegerField(default=-2021),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='deposit_index',
            field=models.IntegerField(default=-2021),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='instrument_index',
            field=models.IntegerField(default=-2021),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='particulars_index',
            field=models.IntegerField(default=-2021),
        ),
        migrations.AlterField(
            model_name='pdfheader',
            name='withdraw_index',
            field=models.IntegerField(default=-2021),
        ),
    ]
