# Generated by Django 3.2.4 on 2021-06-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanpdf', '0004_auto_20210605_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfheader',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='pdfheader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-06-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdfheader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
