# Generated by Django 3.1.7 on 2021-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('sbl', 'standard bank limited'), ('bcbl', 'bangladesh commercial bank limited')], max_length=8)),
                ('date', models.TextField()),
                ('particulars', models.TextField()),
                ('instrument', models.TextField()),
                ('withdraw', models.TextField()),
                ('deposit', models.TextField()),
                ('balance', models.TextField()),
            ],
        ),
    ]
