# Generated by Django 3.1.7 on 2021-06-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headers_temp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='date',
            new_name='dates',
        ),
    ]
