# Generated by Django 3.1.7 on 2021-06-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headers_temp', '0002_auto_20210605_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='bank',
            field=models.CharField(choices=[('sbl', 'standard bank limited'), ('bcbl', 'bangladesh commercial bank limited'), ('exim', 'Export Import Bank of Bangladesh Limited')], max_length=8),
        ),
    ]
