# Generated by Django 3.1.7 on 2021-06-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headers_temp', '0003_auto_20210606_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='instrument',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='particulars',
            field=models.TextField(blank=True, null=True),
        ),
    ]
