# Generated by Django 3.2.4 on 2021-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headers_temp', '0005_auto_20210612_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='bank',
            field=models.CharField(choices=[('sbl', 'standard bank limited'), ('bcbl', 'bangladesh commercial bank limited'), ('exim', 'Export Import Bank of Bangladesh Limited'), ('jbl', 'Jamuna Bank Ltd'), ('ibbl', 'Islami bank')], max_length=8),
        ),
    ]
