# Generated by Django 3.2.4 on 2021-06-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headers_temp', '0006_alter_header_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='bank',
            field=models.CharField(choices=[('sbl', 'standard bank limited'), ('bcbl', 'bangladesh commercial bank limited'), ('exim', 'Export Import Bank of Bangladesh Limited'), ('jbl', 'Jamuna Bank Ltd'), ('ibbl', 'Islami bank Bangladesh Limited'), ('ific', 'international finance investment and commerce bank'), ('pbl', 'Pubali bank limited'), ('prbl', 'Premier bank limited'), ('sbac', 'South bangla agriculture and commerce bank limited'), ('sbl', 'standard bank limited'), ('sibl', 'Social islami bank limited'), ('sjibl', 'Shahjalal islami bank Ltd'), ('sobl', 'SOnali bank limited'), ('ubl', 'uttara bank limited')], max_length=8),
        ),
    ]
