# Generated by Django 3.1.7 on 2021-06-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('shorthand', models.CharField(max_length=8)),
                ('company', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('acctype', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='PdfTables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('particulars', models.TextField(blank=True, null=True)),
                ('instrument', models.TextField(blank=True, null=True)),
                ('withdraw', models.TextField(blank=True, null=True)),
                ('deposit', models.TextField(blank=True, null=True)),
                ('balance', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='showpdf.bankinfo')),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
            },
        ),
    ]
